[build]
  base = "frontend/"
  command = "npm run build"
  publish = "build"

# Handle client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Environment variable configuration
[context.production.environment]
  REACT_APP_API_URL = "https://claimmaster-api.onrender.com"

[context.development.environment]
  REACT_APP_API_URL = "http://localhost:8000"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "https://claimmaster-api.onrender.com" 