services:
  - type: web
    name: claimmaster
    env: python
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --worker-class uvicorn.workers.UvicornWorker --timeout 120
    rootDir: API
    healthCheckPath: /
    autoDeploy: true
    numInstances: 1  # Number of instances to run 